## Nguyễn Hiển Đạt
## MSSV:21127591

Các bước giải thuật Gram-Schmidt như sau:

Bước 1: Chọn một tập hợp các vectơ độc lập tuyến tính S = {v1,…, vk} trong không gian n chiều.

Bước 2: Tính toán vectơ u1 bằng cách chuẩn hóa v1.

Bước 3: Tính toán vectơ u2 bằng cách lấy v2 trừ đi phần chiều của v2 trên u1 và chuẩn hóa kết quả.

Bước 4: Tiếp tục quá trình này cho đến khi ta có được k vectơ trực giao hoặc ortonormal.

In [1]:
import numpy as np
# Bài 1
def show_Matrix(A):
    for i in range(len(A)): 
        for j in range(len(A[0])):
            print("%.2f  " % A[i][j], end="")
        print()
    print()

def transpose(U):
    return [[row[i] for row in U] for i in range(len(U[0]))]

def dot_product(u, v):
    return sum(ui * vi for ui, vi in zip(u, v))

def vector_subtract(u, v):
    return [ui - vi for ui, vi in zip(u, v)]

def scalar_multiply(u, c):
    return [ui * c for ui in u]

def vector_norm(v):
    return sum(vi ** 2 for vi in v) ** 0.5

def qr_decomposition(A):
    A_ = transpose(A)
    n = len(A)
    Q = [[0] * n for _ in range(n)]
    R = [[0] * n for _ in range(n)]

    for i in range(n):
        v = A_[i]
        
        for j in range(i):
            R[j][i] = dot_product(Q[j], A_[i])
            v = vector_subtract(v, scalar_multiply(Q[j], R[j][i]))
        
        R[i][i] = vector_norm(v)
        Q[i] = scalar_multiply(v, 1 / R[i][i])

    return transpose(Q), R



A =[
    [1,1,2],
    [2,-1,1],
    [-2,4,1]
]
Q, R = qr_decomposition(A)

print('A:')
show_Matrix(A)

print('Q:')
show_Matrix(Q)

print('R:')
show_Matrix(R)

print('Nhân ngược lại lấy A:')
result = np.dot(Q,R)
for r in result:
    print(r)

# transpose(U): chuyển vị vécto U
# dot_product(u, v): tính tích vô hướng 2 vécto u và v
# vector_subtract(u, v): lấy vécto u trừ vécto v
# scalar_multiply(u, c): nhân vécto u với một số c
# vector_norm(v): tính chuẩn của vécto v
# Trong hàm qr_decomposition, ta khởi tạo ma trận Q và R với giá trị 0. Áp dụng thuật toán Gram-Schmidt
# cho mỗi cột của ma trận A. R[j][i] là giá trị tích vô hướng của Q[j] và A_[i]. Sau đó tính được trực giao v.
# Chuẩn của v là giá trị của R[i][i] .Tính Q[i] bằng cách lấy v/R[i][i].

A:
1.00  1.00  2.00  
2.00  -1.00  1.00  
-2.00  4.00  1.00  

Q:
0.33  0.67  0.67  
0.67  0.33  -0.67  
-0.67  0.67  -0.33  

R:
3.00  -3.00  0.67  
0.00  3.00  2.33  
0.00  0.00  0.33  

Nhân ngược lại lấy A:
[1. 1. 2.]
[ 2. -1.  1.]
[-2.  4.  1.]


In [2]:
#Bài 2
import numpy as np
import numpy.linalg  

A = numpy.array([
    [1,1,2],
    [2,-1,1],
    [-2,4,1]
])  
Q, R = numpy.linalg.qr(A)

print('A:')
show_Matrix(A)

print('Q:')
show_Matrix(Q)

print('R:')
show_Matrix(R)

print('Nhân ngược lại lấy A:')
result = np.dot(Q,R)
for r in result:
    print(r)

# Nhận xét: Khi dùng hàm có sẵn trong thư viện numpy, ma trận Q và R có dấu khác với khi không dùng thư viện, nhưng
# khi nhân Q với R vẫn ra ma trận A ban đầu.

A:
1.00  1.00  2.00  
2.00  -1.00  1.00  
-2.00  4.00  1.00  

Q:
-0.33  -0.67  0.67  
-0.67  -0.33  -0.67  
0.67  -0.67  -0.33  

R:
-3.00  3.00  -0.67  
0.00  -3.00  -2.33  
0.00  0.00  0.33  

Nhân ngược lại lấy A:
[1. 1. 2.]
[ 2. -1.  1.]
[-2.  4.  1.]
